#!/usr/bin/env bash
set -e

# ANSI escape codes
YELLOW="\033[38;2;120;110;80m"
RESET="\033[0m"

# compiler options
CC="clang"
CFLAGS="-O2 -Wall -Wextra"
LIBS="-lraylib -lm -lrandom"
OUTPUT="main"

run_command() {
  local command="$1"
  echo -e "${YELLOW}$command${RESET}"
  mkdir -p ./out/
  eval $command
}

run_command "$CC ./src/*.c -o ./out/$OUTPUT $CFLAGS $LIBS"
